# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi:  
tidelift:  
community_bridge: Eyes Open Club
liberapay: 
issuehunt: 
otechie: 
custom: paypal.me/eyesopenclub
